---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: secrets-sync
  namespace: flux-system
spec:
  interval: 24h
  ref:
    branch: main
  secretRef:
    name: homelab-secrets-auth
  url: ssh://git@github.com/jetersen/homelab-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets-sync
  namespace: flux-system
spec:
  interval: 24h
  sourceRef:
    kind: GitRepository
    name: secrets-sync
  path: ./
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
