---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-announcement-policy
spec:
  serviceSelector:
    matchExpressions:
      - {key: networking.k8s.io/cilium-disable, operator: NotIn, values: ['true']}
  nodeSelector:
    matchExpressions:
      - {key: networking.k8s.io/cilium-disable, operator: NotIn, values: ['true']}
  externalIPs: false
  loadBalancerIPs: true
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: l2-pool
spec:
  blocks:
  - start: 192.168.1.20
    stop: 192.168.1.30
