---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lan-jetersen-dev
  namespace: cert-manager
spec:
  secretName: lan-jetersen-dev-production-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.lan.jetersen.dev"
  dnsNames:
    - "lan.jetersen.dev"
    - "*.lan.jetersen.dev"
  privateKey:
    algorithm: ECDSA
    size: 384
