apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard.yaml
  - cert-manager.yaml
  - external-dns.yaml
  - home-assistant.yaml
  - monitoring.yaml
  - newt.yaml
  - reflector.yaml
