---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/flux-ks.yaml
  - cilium/flux-ks.yaml
  - envoy-gateway/flux-ks.yaml
  - external-dns/flux-ks.yaml
  - flux-instance/flux-ks.yaml
  - flux-operator/flux-ks.yaml
  - gateway-api/flux-ks.yaml
  - grafana/flux-ks.yaml
  - local-path-provisioner/flux-ks.yaml
  - metrics-server/flux-ks.yaml
  - newt/flux-ks.yaml
  - victoria-logs/flux-ks.yaml
  - victoria-logs-collector/flux-ks.yaml
  - victoria-metrics/flux-ks.yaml
